// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool initNnue({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimpleInitNnue(bytes: bytes);

int analyzePosition({required String fen}) =>
    RustLib.instance.api.crateApiSimpleAnalyzePosition(fen: fen);

String getBestMove({required String fen, required int depth}) =>
    RustLib.instance.api.crateApiSimpleGetBestMove(fen: fen, depth: depth);
