// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool initNnue({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimpleInitNnue(bytes: bytes);

Future<int> analyzePosition({required String fen}) =>
    RustLib.instance.api.crateApiSimpleAnalyzePosition(fen: fen);

Future<String> getBestMove({
  required String fen,
  required int depth,
  required int elo,
}) => RustLib.instance.api.crateApiSimpleGetBestMove(
  fen: fen,
  depth: depth,
  elo: elo,
);

Future<int> evaluateWithSearch({required String fen, required int depth}) =>
    RustLib.instance.api.crateApiSimpleEvaluateWithSearch(
      fen: fen,
      depth: depth,
    );
